### ISSUE TITLE
Using an ELRS receiver there is no Need to Invert S.BUS Signal

### ISSUE THREAD

**Issue by RobertoD91** [macsleep/gamepad#1]
It's no longer necessary to invert the S.BUS signal with the latest ELRS firmware, because they have the option to invert the S.BUS signal.
Tested with a BetaFPV ELRS Micro Receiver with ExpressLRS V3.3.1

I think this is useful information to add to the readme.

PS: thanks for this amazing work!

**Comment by macsleep** [comment]
Hi Roberto, thanks for pointing that out :-) . I had totally missed that the ELRS devs put SBUS back into the receiver firmware. That is a really cool way of hooking up an ELRS receiver to the Teensy. I have always wanted to add CRSF to the SBUS gamepad firmware (the Teensy has the required UART) but haven't come around to doing it.

**Comment by RobertoD91** [comment]
I'm glad to hear that you will continue to work on this project!
If it's helpful, I noticed that someone has already made an ELRS->Gamepad "converter", but for Raspberry Pi Pico.

- https://github.com/mikeneiderhauser/CRSFJoystick
- https://github.com/pfeerick/USB_ELRS_Receiver

**Comment by macsleep** [comment]
@RobertoD91 I have done some testing using a BetaFPV ELRS Lite receiver and updated the documentation. Please let me know if you have any comments?

**Comment by RobertoD91** [comment]
Seems perfect!
Just for info: i think that betafpv ELRS micro receiver pwm is 5v tolerant.

**Comment by macsleep** [comment]
Agree, the pwm receivers have drivers that output whatever voltage you supply them with. You can e.g. drive high voltage (2S) servos with the BetaFPV ELRS Micro. If it can output those voltages then it can probably also accept them as input. 

I have been testing the ELRS Gamepad over the weekend and I haven't had a single fail-safe up to now (I really like this setup :-) ).
